<div class="col-sm-9">
    <h4><small>
        <span class="glyphicon glyphicon-paperclip"></span>  
        Harmonogramy Opłat (<a href="?m=<?php echo $_GET["m"]; ?>&action=create_form">  
        <span class="glyphicon glyphicon-plus"></span> Dodaj </a>) </small></h4>
    <hr>

    <form action="?m=<?php echo $_GET["m"]; ?>&action=nalicz" method="POST">
        <div class="form-group">
            <label>Data Rozliczenia</label>
            <div class='input-group date' id='datetimepicker2'>
                <input type='text' class="form-control" name="evaldate" value="<?php echo date("Y-m-d H:i:s"); ?>" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                <script type="text/javascript">
                    $(function () {
                        $('#datetimepicker2').datetimepicker({
                         format: 'YYYY-MM'
                        });
                    });
                </script>
            </div>
        </div>

       
        <button type="submit" class="btn btn-default">  
                <span class="glyphicon glyphicon-ok"></span> Nalicz Obciążenia Dla Wybranego Miesiąca
        </button>
    </form>

    <br><br>
    
    <table width="100%" class="table table-bordered table-hover" >
        <thead>
        <tr>
        
        <th> <?php sorted_column("Nazwa", "nazwa"); ?> </th>
        <th> <?php sorted_column("Od", "od"); ?> </th>
        <th> <?php sorted_column("Do", "do"); ?> </th>
        <th>   </th>

        </tr>
        </thead>
        <tbody>
        <?php foreach($data["table"] as $row){ ?>
        <tr>
            <td><a href="?m=<?php echo $_GET["m"]; ?>&action=edit&id=<?php echo $row["id"]; ?>">
                <?php echo $row["nazwa"]; ?> </a>
            </td>
            <td><?php echo $row["od"]; ?></td>
            <td><?php echo $row["do"]; ?></td>
            <td>
                <a href="?m=studenci&harmonogramid=<?php echo $row["id"]; ?>">Lista Studentów</a>
            </td>

        </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
