<div class="col-sm-9">
    <h4><small> 
       
        <?php if($_GET["action"]=="create_form"){ ?>
        <i class="glyphicon glyphicon-paperclip"></i> Nowa Harmonogram
        <?php } else { ?>
        <i class="glyphicon glyphicon-edit"></i> Edytuj Harmonogram
        <a href="?m=<?php echo $_GET["m"]; ?>&action=remove&id=<?php echo $_GET["id"]; ?>">
            (<i class="glyphicon glyphicon-remove"></i> Usuń)</a>
        
        <?php } ?>
    </small></h4>
    <hr>
    <form role="form" method="post" 
        action="?m=<?php echo $_GET["m"]; ?>&action=<?php action();?>">   
        <input type="hidden" name="form" value="true">  

        <div class="form-group">
            <label>Nazwa</label>
            <input class="form-control" placeholder="Enter text" name="nazwa" value="<?php get($data,"nazwa"); ?>" >
        </div>    
    
        <div class="form-group">
            <label>Obowiązuje Od</label>
            <div class='input-group date' id='datetimepicker1'>
                <input type='text' class="form-control" name="od" value="<?php get($data,'od',date("Y-m-d H:i:s")); ?>" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                <script type="text/javascript">
                    $(function () {
                        $('#datetimepicker1').datetimepicker({
                         format: 'YYYY-MM-DD'
                        });
                    });
                </script>
            </div>
        </div>
      
       
         <div class="form-group">
            <label>Obowiązuje Do</label>
            <div class='input-group date' id='datetimepicker2'>
                <input type='text' class="form-control" name="do" value="<?php get($data,'do'); ?>" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                <script type="text/javascript">
                    $(function () {
                        $('#datetimepicker2').datetimepicker({
                         format: 'YYYY-MM-DD'
                        });
                    });
                </script>
            </div>
        </div>
      
        <div class="form-group">
            <label>Płatne Każdego Miesiąca W Dniu</label>
            <input class="form-control" placeholder="Enter text" name="platne" value="<?php get($data,"platne"); ?>" >
        </div>    
        <div class="form-group">
            <label>Czas Na Zapłate</label>
            <input class="form-control" placeholder="Enter text" name="czas_na_zaplacenie" value="<?php get($data,"czas_na_zaplacenie"); ?>" >
        </div>    
        
        <div class="form-group">
            <label>Taryfa</label>
            <select name="taryfaid" class="form-control">
                <?php foreach($data["taryfa"]["all"] as $row) { ?>
                <option value="<?php echo $row["id"] ?>" 
                    <?php if ($row["id"] == $data["taryfa"]["active"]) echo "selected"; ?>
                ><?php echo $row["nazwa"] ?></option>
                <?php } ?>
            </select>
        </div>
        

      

        <?php if(isset($data)) { ?>
        <button type="submit" class="btn btn-default">  
            <span class="glyphicon glyphicon-floppy-disk"></span> Zapisz
        </button>
        <?php } else { ?>
        <button type="submit" class="btn btn-default">  
            <span class="glyphicon glyphicon-plus"></span> Dodaj
        </button>
        <?php } ?>

    </form>
 </div> 