<div class="col-sm-9">
    <h4><small> 
       
        <?php if($_GET["action"]=="create_form"){ ?>
        <i class="glyphicon glyphicon-paperclip"></i> Nowa Harmonogram
        <?php } else { ?>
        <i class="glyphicon glyphicon-edit"></i> Edytuj Harmonogram
        <a href="?m=<?php echo $_GET["m"]; ?>&action=remove&id=<?php echo $_GET["id"]; ?>">
            (<i class="glyphicon glyphicon-remove"></i> Usuń)</a>
        
        <?php } ?>
    </small></h4>
    <hr>
    <form role="form" method="post" 
        action="?m=<?php echo $_GET["m"]; ?>&action=<?php action();?>">   
        <input type="hidden" name="form" value="true">  

        <div class="form-group">
            <label>Nazwa</label>
            <input class="form-control" placeholder="Enter text" name="nazwa" value="<?php get($data,"nazwa"); ?>" >
        </div>  
      

        <script>
            // globalna tablica dla 
            var arr = {};

            function gen_range(){
                // tekst z bazy
                var jsonstr = "<?php get_sl($data,"oplaty_miesieczne","");?>";
                var jsonobj = null;
                // slaba walidacja czy to json i go czytam
                if(jsonstr.indexOf("{") >= 0) jsonobj = JSON.parse(jsonstr);
                console.log("gen range");
                // biore zakres dat z fomularza html
                var start = moment($('#od_date').val());
                var stop = moment($('#do_date').val());
                var t = start;
                // czyscze zawartosc formularza
                $('#oplaty_miesiecczne').empty();
                id=0;
                
                // jak z BD dostalem json'a to biore go do tablicy arr
                if(jsonobj)arr=jsonobj;
                while(t<=stop){
                    id++;
                    var mnth= t.format('MMM/YY');
                    if(!arr['monthid-'+mnth]){
                        arr['monthid-'+mnth] = {mth:mnth,sqld:t.format('YYYY-MM-DD'),id:'monthid-'+mnth, value:""};
                    }
                    $('#oplaty_miesiecczne').append('<label for="monthid-"'+mnth+'>' + mnth +'</label>');
                    $('#oplaty_miesiecczne').append('<input class="form-control" id="monthid-'+mnth+'" placeholder="Cena" value="'+arr['monthid-'+mnth].value+'">');
                    $("input[id*='monthid-"+mnth+"']").on('change', function(e){ 
                        arr[event.target.id].value = $(this).val();
                        $('#oplaty_miesieczne_json').val(JSON.stringify(arr));
                    });
                    t = t.add(1,'month');

                }

                $('#oplaty_miesieczne_json').val(JSON.stringify(arr));

            }
        </script>


         
    
        <div class="form-group">
            <label>Obowiązuje Od</label>
            <div class='input-group date' id='datetimepicker1'>
                <input type='text' class="form-control" id="od_date" name="od" value="<?php get($data,'od',date("Y-m-d H:i:s")); ?>"/>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                <script type="text/javascript">
                    $(function () {
                        $('#datetimepicker1').datetimepicker({
                         format: 'YYYY-MM-DD'
                        });

                        $('#datetimepicker1').on('dp.change', function(e){ 
                            gen_range();
                        })
                    });
                </script>
            </div>
        </div>
      
       
         <div class="form-group">
            <label>Obowiązuje Do</label>
            <div class='input-group date' id='datetimepicker2'>
                <input type='text' class="form-control" name="do" id="do_date" value="<?php get($data,'do',date("Y-m-d H:i:s")); ?>" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                <script type="text/javascript">
                    $(function () {
                        $('#datetimepicker2').datetimepicker({
                         format: 'YYYY-MM-DD'
                        });

                        $('#datetimepicker2').on('dp.change', function(e){ 
                            gen_range();
                        })
                    });
                </script>
            </div>
        </div>
      
        <div class="form-group">
            <label>Płatne Każdego Miesiąca W Dniu</label>
            <input class="form-control" placeholder="Enter text" name="platne" value="<?php get($data,"platne", "1"); ?>" >
        </div>    
        <div class="form-group">
            <label>Czas Na Zapłate</label>
            <input class="form-control" placeholder="Enter text" name="czas_na_zaplacenie" value="<?php get($data,"czas_na_zaplacenie","20"); ?>" >
        </div>    
        
        <div class="form-group" >
            <label>Opłata miesięczna</label>
            
            <input class="form-control" id="stala_cena" placeholder="Stała cena cena dla wszystkich miesiecy">
            <input type="hidden" class="form-control" id="oplaty_miesieczne_json" name="oplaty_miesieczne" placeholder="json" value="<?php echo htmlspecialchars($data["oplaty_miesieczne"]); ?>">
            
            <div id="oplaty_miesiecczne" style="padding-left:10px">
            </div>

            <script type="text/javascript">
               $(function () {
                    $('#stala_cena').on('keypress', function(e){ 
                        $("#oplaty_miesiecczne :input").each(function( index ) {
                            $( this ).val($('#stala_cena').val()+String.fromCharCode(e.keyCode));
                        });
                    })
                    gen_range();
                }); 
            </script>
        </div>    

        
          

        <?php if(isset($data)) { ?>
        <button type="submit" class="btn btn-default">  
            <span class="glyphicon glyphicon-floppy-disk"></span> Zapisz
        </button>
        <?php } else { ?>
        <button type="submit" class="btn btn-default">  
            <span class="glyphicon glyphicon-plus"></span> Dodaj
        </button>
        <?php } ?>

    </form>
 </div> 