<div class="col-sm-9">
    <h4><small>
        <span class="glyphicon glyphicon-user"></span>  
        Import (<a href="?m=<?php echo $_GET["m"]; ?>&action=create_form">  
        <span class="glyphicon glyphicon-plus"></span> Dodaj </a>) </small></h4>
    <hr>

    <form role="form" method="post" 
        action="?m=<?php echo $_GET["m"]; ?>&action=upload" enctype="multipart/form-data">   
        <div class="form-group">
        <label>Wybierz plik CSV</label>
        <input type="file" class="form-control" placeholder="Enter text" name="fileToUpload" value="">
        </div>
        <button type="submit" class="btn btn-default">  
            <span class="glyphicon glyphicon-cloud-upload"></span> Dodaj
        </button>
    </form>


    <hr/>
    <h4><small>
        Transkacje do zaakceptowania </small></h4>

    <table width="100%" class="table table-bordered table-hover" >
        <thead>
        <tr>

        <th> <?php sorted_column("Data", "data"); ?> </th>
        <th> <?php sorted_column("Tytuł", "tytul"); ?> </th>
        <th> <?php sorted_column("Kwota", "kwota"); ?> </th>
        <th> <?php sorted_column("Osoba", "osoba"); ?> </th>
        <th> Akcja </th>
    
        </tr>
        </thead>
        <tbody>
        <?php foreach($data["table"] as $row){ ?>
        <tr>
            <td><?php echo $row["data"]; ?></td>
            <td><?php echo $row["tytul"]; ?></td>
            <td><?php echo $row["kwota"]; ?></td>
            <td><?php echo $row["osoba"]; ?></td>
            <td> 
                <a href="?m=<?php echo $_GET["m"]; ?>&action=edit&id=<?php echo $row["id"]; ?>">Edytuj</a> 
                | 
                <a href="?m=<?php echo $_GET["m"]; ?>&action=accept&id=<?php echo $row["id"]; ?>">Zatwierdź</a> 
                | 
                <a href="?m=<?php echo $_GET["m"]; ?>&action=remove&id=<?php echo $row["id"]; ?>">Usuń</a> 
                <br> 
                
            </td> 
        </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

 
