<div class="col-sm-9">
    <h4><small> 
       
        <?php if($_GET["action"]=="create_form"){ ?>
        <i class="glyphicon glyphicon-user"></i> Nowa Osoba
        <?php } else { ?>
        <i class="glyphicon glyphicon-edit"></i> Edytuj Transakcję
        <a href="?m=<?php echo $_GET["m"]; ?>&action=remove&id=<?php echo $_GET["id"]; ?>">
            (<i class="glyphicon glyphicon-remove"></i> Usuń)</a>
        <?php } ?>

    </small></h4>
    <hr>

    <form role="form" method="post" 
        action="?m=<?php echo $_GET["m"]; ?>&action=<?php action($data);?>">   
        <input type="hidden" name="form" value="true">  

        <div class="form-group">
            <label>Tytuł przelewu</label>
            <input class="form-control" placeholder="Enter text" name="tytul" value="<?php get($data,"tytul"); ?>" >
        </div>
        <div class="form-group">
            <label>Data</label>
            <input class="form-control" placeholder="Enter text" name="data" value="<?php get($data,"data"); ?>" >
        </div>
    
        <div class="form-group">
            <label>Kowta przelewu</label>
            <input class="form-control" placeholder="Enter text" name="kwota" value="<?php get($data,"kwota"); ?>" >
        </div>
        
        <div class="form-group">
            <label>Osoba</label>
            <select name="personid" class="form-control">
                <?php foreach($data["person"]["all"] as $row) { ?>
                <option value="<?php echo $row["id"] ?>" 
                    <?php if ($row["phone"] == $data["person"]["active"]) echo "selected"; ?>
                ><?php echo $row["name"] ?></option>
                <?php } ?>
            </select>
        </div>

        <?php if($_GET["action"]=="create_form"){ ?>
        <button type="submit" class="btn btn-default">  
            <span class="glyphicon glyphicon-plus"></span> Dodaj
        </button>
        <?php } else { ?>
        <button type="submit" class="btn btn-default">  
            <span class="glyphicon glyphicon-plus"></span> Zapisz
        </button>
        <?php } ?>

    </form>
 </div>