<div class="col-sm-9">
    <h4><small>
        <span class="glyphicon glyphicon-paperclip"></span>  
        Taryfy (<a href="?m=<?php echo $_GET["m"]; ?>&action=create_form">  
        <span class="glyphicon glyphicon-plus"></span> Dodaj </a>) </small></h4>
    <hr>
    <table width="100%" class="table table-bordered table-hover" >
        <thead>
        <tr>
        <th>ID</th>
        <th>Nazwa</th>
        <th>Wartość</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($data["table"] as $row){ ?>
        <tr>
            <td><?php echo $row["id"]; ?></td>
            <td><a href="?m=<?php echo $_GET["m"]; ?>&action=edit&id=<?php echo $row["id"]; ?>">
                <?php echo $row["nazwa"]; ?>
            </a></td>
            <td><?php echo $row["wartosc"]; ?></td>
            
        </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

 