<div class="col-sm-9">
    <h4><small> 
       
        <?php if($_GET["action"]=="create_form"){ ?>
        <i class="glyphicon glyphicon-usd"></i> Nowe Zobowiązanie
        <?php } else { ?>
        <i class="glyphicon glyphicon-edit"></i> Edytuj Zobowiązanie
        <a href="?m=<?php echo $_GET["m"]; ?>&action=remove&id=<?php echo $_GET["id"]; ?>&pid=<?php echo $_GET["pid"];?>">
            (<i class="glyphicon glyphicon-remove"></i> Usuń)</a>
        
        <?php } ?>
    </small></h4>
    <hr>
    <form role="form" method="post" 
        action="?m=<?php echo $_GET["m"]; ?>&action=<?php action();?>&pid=<?php echo $_GET["pid"]?>">   
        <input type="hidden" name="form" value="true">  

        <div class="form-group">
            <label>Opis</label>
            <input class="form-control" placeholder="Enter text" name="descr" value="<?php get($data,"descr"); ?>" >
        </div>

        <div class="form-group">
            <label>Data</label>
            <input class="form-control" placeholder="Enter text" name="tdate" value="<?php get($data,"tdate", date("Y-m-d H:i:s")); ?>" >
        </div>

        <div class="form-group">
            <label>Wartość</label>
            <input class="form-control" placeholder="Enter text" name="amt" value="<?php get($data,"amt"); ?>" >
        </div>

        <?php if(!isset($_GET["pid"])){ ?>
        <div class="form-group">
            <label>PID</label>
            <input class="form-control" placeholder="Enter text" name="pid" value="<?php get($data,"pid"); ?>" >
        </div>
        <?php }else{ ?>
        <input type="hidden" name="pid" value="<?php echo $_GET["pid"]; ?>" >
        <?php }?>

        <?php if($_GET["action"]=="create_form"){ ?>
        <button type="submit" class="btn btn-default">  
            <span class="glyphicon glyphicon-plus"></span> Dodaj
        </button>
        <?php } else { ?>
        <button type="submit" class="btn btn-default">  
            <span class="glyphicon glyphicon-plus"></span> Zapisz
        </button>
        <?php } ?>

    </form>
 </div>