<div class="col-sm-9">
    <h4><small>
        <span class="glyphicon glyphicon-user"></span>  
        Studenci/Osoby (<a href="?m=<?php echo $_GET["m"]; ?>&action=create_form">  
        <span class="glyphicon glyphicon-plus"></span> Dodaj </a>) </small></h4>
    <hr>
    <table width="100%" class="table table-bordered table-hover" >
        <thead>
        <tr>

        <th> <?php sorted_column("Nazwisko Imię", "last"); ?> </th>
        <th> <?php sorted_column("Telefon", "phone"); ?> </th>
        <th> <?php sorted_column("Grupa", "grupa"); ?> </th>
        <th> <?php sorted_column("Saldo", "saldo"); ?> </th>
    
        </tr>
        </thead>
        <tbody>
        <?php foreach($data["table"] as $row){ ?>
        <tr>
            <td><a href="?m=<?php echo $_GET["m"]; ?>&action=edit&id=<?php echo $row["id"]; ?>">
                <?php echo $row["last"]; ?> </a></td>
            <td><?php echo $row["phone"]; ?></td>
            <td><?php echo $row["grupa"]; ?></td>
            <td onclick="window.location.href='?m=payments&action=list&pid=<?php echo $row["id"]; ?>'">
                <?php echo $row["saldo"]; ?> </td>
        </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

 