<div class="col-sm-9">
    <h4><small>
        <span class="glyphicon glyphicon-user"></span>  
        Studenci/Osoby (<a href="?m=<?php echo $_GET["m"]; ?>&action=create_form">  
        <span class="glyphicon glyphicon-plus"></span> Dodaj </a>) </small></h4>
    <hr>

    <div class="form-group">
            <label>Grupa</label>
            <select name="groupid" id="groupid" class="form-control" onchange="" >
                <?php foreach($data["grupa"]["all"] as $row) { ?>
                <option value="<?php echo $row["id"] ?>" 
                    <?php if ($row["id"] == $data["grupa"]["active"]) echo "selected"; ?>
                ><?php echo $row["name"] ?></option>
                <?php } ?>
            </select>
    </div>

    <script type="text/javascript">
        function replaceUrlParam(url, paramName, paramValue)
        {
            if (paramValue == null) {
                paramValue = '';
            }
            var pattern = new RegExp('\\b('+paramName+'=).*?(&|$)');
            if (url.search(pattern)>=0) {
                return url.replace(pattern,'$1' + paramValue + '$2');
            }
            url = url.replace(/\?$/,'');
            return url + (url.indexOf('?')>0 ? '&' : '?') + paramName + '=' + paramValue;
        }

        $(function () {
            $('#groupid').on('change', function(e){ 
                var hrf = window.location.href;
                window.location.href=(replaceUrlParam(hrf,"groupid",e.target.value));
            })
        });
    </script>


    <table width="100%" class="table table-bordered table-hover" >
        <thead>
        <tr>

        <th> <?php sorted_column("Nazwisko Imię", "last"); ?> </th>
        <th> <?php sorted_column("Telefon", "phone"); ?> </th>
        <!--<th> <?php sorted_column("Grupa", "grupa"); ?> </th>-->
        <th> <?php sorted_column("Saldo", "saldo"); ?> </th>
        <th> <?php sorted_column("Zaległość", "zaleglosc"); ?> </th>
        <th> <?php sorted_column("Data urodzenia", "dataurodzenia"); ?> </th>
        <th> Akcja </th>
    
        </tr>
        </thead>
        <tbody>
        <?php foreach($data["table"] as $row){ ?>
        <tr>
            <td><a href="?m=<?php echo $_GET["m"]; ?>&action=edit&id=<?php echo $row["id"]; ?>">
                <?php echo $row["last"]; ?> </a></td>
            <td><?php echo $row["phone"]; ?></td>
           <!-- <td><?php echo $row["grupa"]; ?></td>-->
            <td onclick="window.location.href=''">
                <?php echo $row["saldo"]; ?> 
            </td>
             <td><?php echo $row["zaleglosc"]<0?$row["zaleglosc"]:0; ?></td>
             <td><?php echo $row["dataurodzenia"]; ?></td>
            <td>
                <a href="?m=payments&action=list&pid=<?php echo $row["id"]; ?>" > szczegóły </a>
            </td>
        </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

 